const recipes = [
  {
    id: 1,
    name: "Pollo con arroz y verduras",
    ingredients: {
      carbs: [{ name: "arroz integral" }],
      proteins: [{ name: "pechuga de pollo" }],
      vegetables: [
        { name: "zanahoria" },
        { name: "brócoli" },
        { name: "pimiento rojo" },
      ],
    },
    instructions:
      "Cocinar el arroz. Saltear las verduras y el pollo. Mezclar y servir.",
    time: 40,
    servings: 2,
    image: "https://ejemplo.com/imagenes/pollo-arroz.jpg",
    category: "Plato principal",
    difficulty: "Fácil",
    tags: ["saludable", "sin gluten", "alto en proteína"],
  },
  {
    id: 2,
    name: "Ensalada de quinoa con garbanzos",
    ingredients: {
      carbs: [{ name: "quinoa" }],
      proteins: [{ name: "garbanzos cocidos" }],
      vegetables: [
        { name: "pepino" },
        { name: "tomate cherry" },
        { name: "espinaca" },
      ],
    },
    instructions:
      "Cocinar la quinoa. Mezclar con los garbanzos y los vegetales. Aliñar.",
    time: 25,
    servings: 4,
    image: "https://ejemplo.com/imagenes/ensalada-quinoa.jpg",
    category: "Ensalada",
    difficulty: "Muy fácil",
    tags: ["vegano", "fresco", "rico en fibra"],
  },
  {
    id: 3,
    name: "Tacos de carne con vegetales",
    ingredients: {
      carbs: [{ name: "tortillas de maíz" }],
      proteins: [{ name: "carne molida de res" }],
      vegetables: [
        { name: "lechuga" },
        { name: "tomate" },
        { name: "aguacate" },
      ],
    },
    instructions:
      "Cocinar la carne con especias. Calentar las tortillas. Armar los tacos con todo.",
    time: 30,
    servings: 3,
    image: "https://ejemplo.com/imagenes/tacos-carne.jpg",
    category: "Comida mexicana",
    difficulty: "Media",
    tags: ["sabroso", "rápido", "con carne"],
  },
  {
    id: 4,
    name: "Salmón al horno con patatas y espárragos",
    ingredients: {
      carbs: [{ name: "patatas" }],
      proteins: [{ name: "salmón" }],
      vegetables: [{ name: "espárragos" }, { name: "limón" }, { name: "ajo" }],
    },
    instructions:
      "Hornear el salmón con patatas y espárragos. Servir caliente.",
    time: 30,
    servings: 2,
    image: "https://ejemplo.com/imagenes/salmon-horno.jpg",
    category: "Cena",
    difficulty: "Fácil",
    tags: ["omega 3", "sin gluten", "horno"],
  },
  {
    id: 5,
    name: "Bowl de tofu con arroz y brócoli",
    ingredients: {
      carbs: [{ name: "arroz jazmín" }],
      proteins: [{ name: "tofu firme" }],
      vegetables: [{ name: "brócoli" }, { name: "zanahoria" }],
    },
    instructions:
      "Cocinar el arroz y el tofu. Agregar vegetales salteados. Servir en bowl.",
    time: 35,
    servings: 2,
    image: "https://ejemplo.com/imagenes/bowl-tofu.jpg",
    category: "Vegano",
    difficulty: "Fácil",
    tags: ["plant-based", "bajo en grasa", "rico en proteína"],
  },
  {
    id: 6,
    name: "Tortilla de claras con espinaca y pan integral",
    ingredients: {
      carbs: [{ name: "pan integral" }],
      proteins: [{ name: "claras de huevo" }],
      vegetables: [{ name: "espinaca" }, { name: "tomate" }],
    },
    instructions:
      "Hacer una tortilla de claras con espinaca. Servir con pan integral.",
    time: 15,
    servings: 1,
    image: "https://ejemplo.com/imagenes/omelette-espinaca.jpg",
    category: "Desayuno",
    difficulty: "Muy fácil",
    tags: ["fitness", "rápido", "bajo en calorías"],
  },
  {
    id: 7,
    name: "Pasta integral con atún y tomate",
    ingredients: {
      carbs: [{ name: "pasta integral" }],
      proteins: [{ name: "atún en lata" }],
      vegetables: [{ name: "tomate" }, { name: "ajo" }, { name: "perejil" }],
    },
    instructions:
      "Cocinar la pasta. Mezclar con atún y salsa de tomate casera.",
    time: 20,
    servings: 2,
    image: "https://ejemplo.com/imagenes/pasta-atun.jpg",
    category: "Pasta",
    difficulty: "Fácil",
    tags: ["rápido", "económico", "rico en proteína"],
  },
  {
    id: 8,
    name: "Wrap de pollo con aguacate y hojas verdes",
    ingredients: {
      carbs: [{ name: "tortilla integral" }],
      proteins: [{ name: "pollo a la plancha" }],
      vegetables: [
        { name: "aguacate" },
        { name: "rúcula" },
        { name: "lechuga" },
      ],
    },
    instructions:
      "Cortar el pollo en tiras, mezclar con vegetales y armar el wrap.",
    time: 15,
    servings: 1,
    image: "https://ejemplo.com/imagenes/wrap-pollo.jpg",
    category: "Snack",
    difficulty: "Fácil",
    tags: ["para llevar", "ligero", "fresco"],
  },
  {
    id: 9,
    name: "Hamburguesas de lentejas con ensalada",
    ingredients: {
      carbs: [{ name: "pan de hamburguesa integral" }],
      proteins: [{ name: "lentejas cocidas" }],
      vegetables: [
        { name: "lechuga" },
        { name: "tomate" },
        { name: "cebolla" },
      ],
    },
    instructions:
      "Formar hamburguesas con lentejas. Cocinar y servir con pan y ensalada.",
    time: 35,
    servings: 4,
    image: "https://ejemplo.com/imagenes/hamburguesas-lentejas.jpg",
    category: "Vegetariana",
    difficulty: "Media",
    tags: ["sin carne", "alto en fibra", "plant-based"],
  },
  {
    id: 10,
    name: "Wok de fideos con cerdo y verduras",
    ingredients: {
      carbs: [{ name: "fideos integrales" }],
      proteins: [{ name: "lomo de cerdo" }],
      vegetables: [
        { name: "pimiento" },
        { name: "calabacín" },
        { name: "brotes de soja" },
      ],
    },
    instructions: "Cocinar todo al wok con salsa de soja. Servir caliente.",
    time: 25,
    servings: 3,
    image: "https://ejemplo.com/imagenes/wok-cerdo.jpg",
    category: "Fusión asiática",
    difficulty: "Media",
    tags: ["salteado", "rápido", "sabroso"],
  },
  {
    id: 11,
    name: "Tortilla de avena con espinaca",
    ingredients: {
      carbs: [{ name: "avena" }],
      proteins: [{ name: "huevo" }],
      vegetables: [{ name: "espinaca" }, { name: "cebolla" }],
    },
    instructions: "Mezclar todo y cocinar como tortilla en sartén.",
    time: 20,
    servings: 2,
    image: "https://ejemplo.com/imagenes/tortilla-avena.jpg",
    category: "Vegetariana",
    difficulty: "Fácil",
    tags: ["alto en fibra", "saludable"],
  },
  {
    id: 12,
    name: "Arroz chaufa de pollo",
    ingredients: {
      carbs: [{ name: "arroz blanco" }],
      proteins: [{ name: "pollo" }, { name: "huevo" }],
      vegetables: [{ name: "cebolla china" }, { name: "zanahoria" }],
    },
    instructions: "Saltear todo junto y agregar salsa de soya.",
    time: 30,
    servings: 3,
    image: "https://ejemplo.com/imagenes/chaufa-pollo.jpg",
    category: "Fusión peruana",
    difficulty: "Media",
    tags: ["sabroso", "rápido", "popular"],
  },
  {
    id: 13,
    name: "Cuscús con garbanzos y verduras al horno",
    ingredients: {
      carbs: [{ name: "cuscús integral" }],
      proteins: [{ name: "garbanzos cocidos" }],
      vegetables: [
        { name: "berenjena" },
        { name: "pimiento rojo" },
        { name: "calabacín" },
      ],
    },
    instructions:
      "Hornear las verduras, mezclar con el cuscús cocido y garbanzos.",
    time: 35,
    servings: 4,
    image: "https://ejemplo.com/imagenes/cuscus-garbanzos.jpg",
    category: "Plato principal",
    difficulty: "Media",
    tags: ["vegano", "rico en fibra", "colorido"],
  },
  {
    id: 14,
    name: "Buddha bowl con huevo poché",
    ingredients: {
      carbs: [{ name: "arroz integral" }],
      proteins: [{ name: "huevo poché" }],
      vegetables: [
        { name: "espinaca" },
        { name: "zanahoria rallada" },
        { name: "remolacha cocida" },
      ],
    },
    instructions: "Armar un bowl con los ingredientes cocidos y huevo encima.",
    time: 25,
    servings: 2,
    image: "https://ejemplo.com/imagenes/buddha-bowl.jpg",
    category: "Veggie",
    difficulty: "Fácil",
    tags: ["equilibrado", "bowl", "saludable"],
  },
  {
    id: 15,
    name: "Pizza de avena con verduras y queso",
    ingredients: {
      carbs: [{ name: "base de avena" }],
      proteins: [{ name: "queso bajo en grasa" }],
      vegetables: [
        { name: "tomate" },
        { name: "cebolla morada" },
        { name: "rúcula" },
      ],
    },
    instructions: "Preparar la base, agregar ingredientes y hornear.",
    time: 40,
    servings: 2,
    image: "https://ejemplo.com/imagenes/pizza-avena.jpg",
    category: "Cena",
    difficulty: "Media",
    tags: ["alternativa saludable", "bajo en carbohidratos"],
  },
  {
    id: 16,
    name: "Sopa de lentejas con zanahoria y apio",
    ingredients: {
      carbs: [{ name: "lentejas" }],
      proteins: [{ name: "lentejas" }], // doble función aquí
      vegetables: [
        { name: "zanahoria" },
        { name: "apio" },
        { name: "cebolla" },
      ],
    },
    instructions:
      "Hervir todo junto hasta que esté bien cocido. Servir caliente.",
    time: 45,
    servings: 4,
    image: "https://ejemplo.com/imagenes/sopa-lentejas.jpg",
    category: "Sopa",
    difficulty: "Fácil",
    tags: ["caliente", "confort", "rico en hierro"],
  },
  {
    id: 17,
    name: "Arroz con huevo y espinaca",
    ingredients: {
      carbs: [{ name: "arroz blanco" }],
      proteins: [{ name: "huevo" }],
      vegetables: [{ name: "espinaca" }, { name: "cebolla" }],
    },
    instructions: "Cocinar el arroz. Freír el huevo y saltear con espinaca.",
    time: 20,
    servings: 2,
    image: "https://ejemplo.com/imagenes/arroz-huevo.jpg",
    category: "Rápido",
    difficulty: "Muy fácil",
    tags: ["express", "económico", "rico"],
  },
  {
    id: 18,
    name: "Pan pita con hummus y vegetales",
    ingredients: {
      carbs: [{ name: "pan pita integral" }],
      proteins: [{ name: "hummus de garbanzos" }],
      vegetables: [{ name: "pepino" }, { name: "tomate" }, { name: "rúcula" }],
    },
    instructions: "Untar pan con hummus y agregar vegetales frescos.",
    time: 10,
    servings: 1,
    image: "https://ejemplo.com/imagenes/pita-hummus.jpg",
    category: "Snack",
    difficulty: "Muy fácil",
    tags: ["ligero", "vegano", "fácil"],
  },
  {
    id: 19,
    name: "Fajitas de ternera con pimientos",
    ingredients: {
      carbs: [{ name: "tortillas integrales" }],
      proteins: [{ name: "filetes de ternera" }],
      vegetables: [
        { name: "pimiento rojo" },
        { name: "cebolla" },
        { name: "aguacate" },
      ],
    },
    instructions: "Cocinar la ternera y las verduras, armar fajitas.",
    time: 30,
    servings: 3,
    image: "https://ejemplo.com/imagenes/fajitas-ternera.jpg",
    category: "Comida mexicana",
    difficulty: "Media",
    tags: ["sabroso", "alto en proteína"],
  },
  {
    id: 20,
    name: "Tabulé con trigo bulgur y perejil",
    ingredients: {
      carbs: [{ name: "trigo bulgur" }],
      proteins: [{ name: "garbanzos" }],
      vegetables: [
        { name: "perejil fresco" },
        { name: "tomate" },
        { name: "pepino" },
      ],
    },
    instructions:
      "Hidratar el trigo, mezclar con vegetales picados y garbanzos.",
    time: 20,
    servings: 4,
    image: "https://ejemplo.com/imagenes/tabule.jpg",
    category: "Ensalada",
    difficulty: "Fácil",
    tags: ["libanés", "refrescante", "vegano"],
  },
];

module.exports = recipes;
